services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pathforge
      POSTGRES_USER: pathforge
      POSTGRES_PASSWORD: pathforge794*
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
