import { CareerProfile, CareerSlug } from "../services/career-discovery.service";

export const CAREER_PROFILES: Record<CareerSlug, CareerProfile> = {
  frontend: {
    title: "Frontend Developer",
    relatedTechnologies: ["html_css", "javascript", "typescript", "react", "vue", "angular", "git"],
    relatedProjects: ["web_apps", "games"],
    relatedIndustries: ["web", "fintech", "healthtech", "gaming"],
    relatedPreferences: ["visual"],
    marketDemand: "very_high",
    averageSalary: "$50,000 - $120,000 USD/año",
    remoteOpportunities: "excellent",
    baseMonthsToLearn: { none: 12, beginner: 8, intermediate: 4, advanced: 2 },
    requiredTechnologies: ["html_css", "javascript", "react"],
  },
  backend: {
    title: "Backend Developer",
    relatedTechnologies: ["python", "java", "csharp", "node", "go", "sql", "nosql", "docker", "git"],
    relatedProjects: ["apis", "automation"],
    relatedIndustries: ["web", "fintech", "healthtech"],
    relatedPreferences: ["logical"],
    marketDemand: "very_high",
    averageSalary: "$55,000 - $130,000 USD/año",
    remoteOpportunities: "excellent",
    baseMonthsToLearn: { none: 14, beginner: 10, intermediate: 5, advanced: 2 },
    requiredTechnologies: ["sql", "node", "docker"],
  },
  fullstack: {
    title: "Full-Stack Developer",
    relatedTechnologies: ["html_css", "javascript", "typescript", "react", "node", "sql", "git", "docker"],
    relatedProjects: ["web_apps", "apis"],
    relatedIndustries: ["web", "fintech", "healthtech"],
    relatedPreferences: ["visual", "logical"],
    marketDemand: "very_high",
    averageSalary: "$60,000 - $140,000 USD/año",
    remoteOpportunities: "excellent",
    baseMonthsToLearn: { none: 18, beginner: 14, intermediate: 8, advanced: 4 },
    requiredTechnologies: ["html_css", "javascript", "node", "sql"],
  },
  devops: {
    title: "DevOps / Cloud Engineer",
    relatedTechnologies: ["linux", "docker", "kubernetes", "aws", "azure", "gcp", "python", "git"],
    relatedProjects: ["infrastructure", "automation"],
    relatedIndustries: ["cloud", "web", "fintech"],
    relatedPreferences: ["infrastructure"],
    marketDemand: "very_high",
    averageSalary: "$70,000 - $160,000 USD/año",
    remoteOpportunities: "excellent",
    baseMonthsToLearn: { none: 16, beginner: 12, intermediate: 6, advanced: 3 },
    requiredTechnologies: ["linux", "docker", "aws"],
  },
  data_science: {
    title: "Data Scientist / ML Engineer",
    relatedTechnologies: ["python", "sql", "nosql"],
    relatedProjects: ["data_analysis", "ai_ml", "automation"],
    relatedIndustries: ["data", "fintech", "healthtech"],
    relatedPreferences: ["data", "logical"],
    marketDemand: "high",
    averageSalary: "$65,000 - $150,000 USD/año",
    remoteOpportunities: "good",
    baseMonthsToLearn: { none: 18, beginner: 14, intermediate: 8, advanced: 4 },
    requiredTechnologies: ["python", "sql"],
  },
  mobile: {
    title: "Mobile Developer",
    relatedTechnologies: ["javascript", "typescript", "react", "java"],
    relatedProjects: ["mobile_apps"],
    relatedIndustries: ["mobile", "gaming", "fintech", "healthtech"],
    relatedPreferences: ["visual"],
    marketDemand: "high",
    averageSalary: "$55,000 - $130,000 USD/año",
    remoteOpportunities: "good",
    baseMonthsToLearn: { none: 14, beginner: 10, intermediate: 5, advanced: 2 },
    requiredTechnologies: ["javascript", "react"],
  },
  cybersecurity: {
    title: "Cybersecurity Engineer",
    relatedTechnologies: ["linux", "python", "sql", "git"],
    relatedProjects: ["infrastructure", "automation"],
    relatedIndustries: ["security", "fintech", "healthtech"],
    relatedPreferences: ["security", "logical"],
    marketDemand: "very_high",
    averageSalary: "$70,000 - $160,000 USD/año",
    remoteOpportunities: "good",
    baseMonthsToLearn: { none: 20, beginner: 16, intermediate: 10, advanced: 6 },
    requiredTechnologies: ["linux", "python"],
  },
  qa: {
    title: "QA Engineer",
    relatedTechnologies: ["javascript", "python", "sql", "git"],
    relatedProjects: ["web_apps", "apis", "mobile_apps"],
    relatedIndustries: ["web", "mobile", "fintech"],
    relatedPreferences: ["logical"],
    marketDemand: "high",
    averageSalary: "$45,000 - $100,000 USD/año",
    remoteOpportunities: "good",
    baseMonthsToLearn: { none: 10, beginner: 7, intermediate: 4, advanced: 2 },
    requiredTechnologies: ["javascript", "sql"],
  },
};